# Generated by Django 3.2.6 on 2021-08-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_ons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Car_variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_name', models.CharField(max_length=20)),
                ('time_to_60', models.CharField(max_length=20)),
                ('top_speed', models.CharField(max_length=20)),
                ('peak_power', models.CharField(max_length=20)),
                ('start_price', models.CharField(max_length=20)),
                ('start_range', models.CharField(max_length=20)),
                ('cargo_capacity', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wheels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='cars',
            name='starts_at',
        ),
        migrations.AddField(
            model_name='cars',
            name='start_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='time_to_60',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_image',
            field=models.ImageField(max_length=300, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cars',
            name='model_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='peak_power',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='top_speed',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='interior',
            field=models.ManyToManyField(to='carsApp.Interior'),
        ),
        migrations.AddField(
            model_name='cars',
            name='paint',
            field=models.ManyToManyField(to='carsApp.Paint'),
        ),
        migrations.AddField(
            model_name='cars',
            name='wheels',
            field=models.ManyToManyField(to='carsApp.Wheels'),
        ),
    ]
