# Generated by Django 3.2.6 on 2021-08-20 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsApp', '0003_auto_20210820_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_variation',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsApp.cars'),
        ),
    ]
