# Generated by Django 3.2.6 on 2021-08-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsApp', '0005_auto_20210820_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='carvariation',
            name='name',
            field=models.CharField(choices=[('plaid', 'plaid'), ('plaid+', 'plaid+'), ('long range', 'long range')], default='plaid', max_length=20),
        ),
    ]
