# Generated by Django 3.2.6 on 2021-08-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsApp', '0006_auto_20210821_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('Time_to_60', models.CharField(max_length=10, null=True)),
                ('base_price', models.IntegerField(default=0, null=True)),
                ('start_range', models.CharField(max_length=20, null=True)),
                ('peak_power', models.CharField(max_length=20, null=True)),
                ('top_speed', models.CharField(max_length=20, null=True)),
                ('weight', models.CharField(max_length=20, null=True)),
                ('cargo_capacity', models.CharField(max_length=20, null=True)),
                ('power_train', models.CharField(max_length=20, null=True)),
                ('acceleration', models.CharField(max_length=20, null=True)),
                ('drag_coefficient', models.CharField(max_length=20, null=True)),
                ('wheels', models.CharField(max_length=20, null=True)),
                ('charging', models.CharField(max_length=20, null=True)),
                ('img_url', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
