# Generated by Django 3.2.6 on 2021-08-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsApp', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='add_on',
            field=models.ManyToManyField(to='carsApp.AddOn'),
        ),
        migrations.AddField(
            model_name='order',
            name='interior',
            field=models.ManyToManyField(to='carsApp.Interior'),
        ),
        migrations.AddField(
            model_name='order',
            name='paint',
            field=models.ManyToManyField(to='carsApp.Paint'),
        ),
        migrations.AddField(
            model_name='order',
            name='wheel',
            field=models.ManyToManyField(to='carsApp.Wheel'),
        ),
    ]
