# Generated by Django 3.2.6 on 2021-08-25 07:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsApp', '0009_auto_20210821_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Time_to_60',
        ),
        migrations.RemoveField(
            model_name='order',
            name='acceleration',
        ),
        migrations.RemoveField(
            model_name='order',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cargo_capacity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='charging',
        ),
        migrations.RemoveField(
            model_name='order',
            name='drag_coefficient',
        ),
        migrations.RemoveField(
            model_name='order',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='peak_power',
        ),
        migrations.RemoveField(
            model_name='order',
            name='power_train',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='top_speed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wheels',
        ),
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsApp.car'),
        ),
        migrations.AddField(
            model_name='order',
            name='car_variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsApp.carvariation'),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
    ]
